#OBJS specifies which files to compile as part of the project 
OBJS = main.c gl3w/gl3w.c
#OBJ_NAME specifies the name of our exectuable 
OBJ_NAME = pplane
#This is the target that compiles our executable 
all : $(OBJS) 
	gcc -g $(OBJS) -Igl3w/ -IC:\mingw_dev_lib\include -LC:\mingw_dev_lib\lib -w -Wl,-subsystem,windows -lmingw32 -lSDL2main -lSDL2 -lopengl32 -o $(OBJ_NAME)
