OBJS = pplane.c gl3w/gl3w.c
OBJ_NAME = build/pplane

all : $(OBJS)
	IF NOT EXIST build mkdir build
	gcc -g $(OBJS) -Isdl/include/ -Lsdl/lib -Igl3w\ -w -Wl,-subsystem,windows -lmingw32 -lopengl32 -lSDL2main -lSDL2 -o $(OBJ_NAME)
	copy "sdl\bin\SDL2.dll" "build\SDL2.dll"
# sdl: 
# 	wget http://libsdl.org/release/SDL2-devel-2.0.4-mingw.tar.gz
# 	tar xvf SDL2-devel-2.0.4-mingw.tar.gz
# 	cp SDL2-2.0.4/x86_64-mingw32 sdl
